//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class UR3JointStatesMsg : Message
    {
        public const string k_RosMessageName = "ur3_moveit/UR3JointStates";
        public override string RosMessageName => k_RosMessageName;

        public double[] joint_position;

        public UR3JointStatesMsg()
        {
            this.joint_position = new double[6];
        }

        public UR3JointStatesMsg(double[] joint_position)
        {
            this.joint_position = joint_position;
        }

        public static UR3JointStatesMsg Deserialize(MessageDeserializer deserializer) => new UR3JointStatesMsg(deserializer);

        private UR3JointStatesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_position, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_position);
        }

        public override string ToString()
        {
            return "UR3JointStatesMsg: " +
            "\njoint_position: " + System.String.Join(", ", joint_position.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
