//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class UR3MoveitJointsMsg : Message
    {
        public const string k_RosMessageName = "ur3_moveit/UR3MoveitJoints";
        public override string RosMessageName => k_RosMessageName;

        public double joint_00;
        public double joint_01;
        public double joint_02;
        public double joint_03;
        public double joint_04;
        public double joint_05;
        public Geometry.PoseMsg pick_pose;
        public Geometry.PoseMsg place_pose;

        public UR3MoveitJointsMsg()
        {
            this.joint_00 = 0.0;
            this.joint_01 = 0.0;
            this.joint_02 = 0.0;
            this.joint_03 = 0.0;
            this.joint_04 = 0.0;
            this.joint_05 = 0.0;
            this.pick_pose = new Geometry.PoseMsg();
            this.place_pose = new Geometry.PoseMsg();
        }

        public UR3MoveitJointsMsg(double joint_00, double joint_01, double joint_02, double joint_03, double joint_04, double joint_05, Geometry.PoseMsg pick_pose, Geometry.PoseMsg place_pose)
        {
            this.joint_00 = joint_00;
            this.joint_01 = joint_01;
            this.joint_02 = joint_02;
            this.joint_03 = joint_03;
            this.joint_04 = joint_04;
            this.joint_05 = joint_05;
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
        }

        public static UR3MoveitJointsMsg Deserialize(MessageDeserializer deserializer) => new UR3MoveitJointsMsg(deserializer);

        private UR3MoveitJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_00);
            deserializer.Read(out this.joint_01);
            deserializer.Read(out this.joint_02);
            deserializer.Read(out this.joint_03);
            deserializer.Read(out this.joint_04);
            deserializer.Read(out this.joint_05);
            this.pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_00);
            serializer.Write(this.joint_01);
            serializer.Write(this.joint_02);
            serializer.Write(this.joint_03);
            serializer.Write(this.joint_04);
            serializer.Write(this.joint_05);
            serializer.Write(this.pick_pose);
            serializer.Write(this.place_pose);
        }

        public override string ToString()
        {
            return "UR3MoveitJointsMsg: " +
            "\njoint_00: " + joint_00.ToString() +
            "\njoint_01: " + joint_01.ToString() +
            "\njoint_02: " + joint_02.ToString() +
            "\njoint_03: " + joint_03.ToString() +
            "\njoint_04: " + joint_04.ToString() +
            "\njoint_05: " + joint_05.ToString() +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
