//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class UR3TrajectoryMsg : Message
    {
        public const string k_RosMessageName = "ur3_moveit/UR3Trajectory";
        public override string RosMessageName => k_RosMessageName;

        public Moveit.RobotTrajectoryMsg[] trajectory;

        public UR3TrajectoryMsg()
        {
            this.trajectory = new Moveit.RobotTrajectoryMsg[0];
        }

        public UR3TrajectoryMsg(Moveit.RobotTrajectoryMsg[] trajectory)
        {
            this.trajectory = trajectory;
        }

        public static UR3TrajectoryMsg Deserialize(MessageDeserializer deserializer) => new UR3TrajectoryMsg(deserializer);

        private UR3TrajectoryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectory, Moveit.RobotTrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.trajectory);
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "UR3TrajectoryMsg: " +
            "\ntrajectory: " + System.String.Join(", ", trajectory.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
