scrap:
  add_noise:
    image_topic: "/panda_camera/depth/image_raw"
    noise_depth_topic: "/noisy/depth"
    noise_rgb_topic: "/noisy/color"
    noise_type: "gaussian"
    is_relative: true
    gaussian:
      mean: 0.0
      stddev: 0.0025
      cutoff: 1.0
  path_follow:
    interactive_execution: true # Whether execution waits for user to enter confirmation before moving
    planning_time: 1.0          # Make it quick with active vision
    downsample_leaf_size: -1.0
    normal_nn_count: 120
    outlier_removal:
      stddev_thresh: 0.1
      mean_k: -1
    sample_execution: false
    distance_from_scrap: 0.15
    visualization:
      view_target: true
      view_normal: true
    use_method: "active"
    active_vision:
      octomap_res: 0.025
      camera:
        res_y: 640
        res_x: 480
        focal_length: 554.25469
      ray_length: 0.5
      frontier_bounding_box: 6
      threads: 10
      prox_cutoff_thresh: 0.1
      optimized: true
    curve_fitting:
      smoothness: 1.0
      control_pts: 20
    depth_topic: "/panda_camera/depth/points"
    save_points: false
    save_points_path: "/tmp/points.csv"
    filter:
      lower: 70
      secondary_threshold: 30
