scrap:
  add_noise:
    noise_type: "none"
  path_follow:
    use_method: "active"
    interactive_execution: true # Whether execution waits for user to enter confirmation before moving
    downsample_leaf_size: 0.001
    normal_nn_count: 120
    outlier_removal:
      mean_k: 0
      stddev_thresh: 100.0
    sample_execution: false
    distance_from_scrap: 0.37 # Minimum is 0.26
    depth_topic: "/camera/depth/color/points"
    save_points: true
    save_points_path: "/tmp/points.csv"
    initial_joint_config:       # Initial position to move towards
      - 0.0
      - -0.70
      - 0.0
      - -0.78
      - 0.0
      - 0.78
      - 0.78
    filter:
      color: "r"                # Which field to filter the curve on
      lower: 150                  # Lower bound
      upper: 255                # Upper bound
      secondary_threshold: 120  # Other color fields
    use_pcl_nurbs: false
    curve_fitting:
      control_pts: 50         # Number of control points
      smoothness: 0.0       # Smoothness constraint of the curve
      radius: 1.0             # Initial curve radius
      min_cutoff_dist: 0.01     # Cutoff curve if too far from any point
      skel_leaf_size: 0.008
    active_vision:
      use_threads: 5
