origami_sim:
# Low level controller settings
  motor_conversion: 0.1 # default = 0.1

# Simulation parameters
  control_rate: 10
  num_of_modules: 1
  init_cable_lengths: [[80.0,80.0,81.0]]
  # num_of_modules: 2
  # init_cable_lengths: [[80.0,80.0,160.0],[160.0,160.0,80.0]]

# Visualization settings
  points_per_segment: 10