origamibot :
  gazebo_camera:
    focus: 178.76  # Focal length from Intrinsic Matrix 
    cx_intrinsic: 150.5 # cx from Intrinsic Matrix
    cy_intrinsic: 150.5 # cy from Intrinsic Matrix
    depth: 1.83 # measured Depth from Camera centre to end effector
  
  robot_params:
    module_d: 40 #Radius in mm
    no_of_actuators: 3
    no_of_modules: 1

  
  control:
    no_of_features: 2
    rate: 10 # control loop rate
    goal_pos_x: 100       # 
    goal_pos_y: 350     # 
    goal_pos_z: 0     # 
    # right(400,250) = left(250,250), middle (280,150) (350,150)


  mpc:
    mpc_steps: 4  # prediction horizon
    mpc_sample_time: 0.1 # 100ms -10hz
    w_pixel_x: 0.02 # weight to Pixel error in X -0.001
    w_pixel_y: 0.02 # weight to Pixel error in Y -0.001
    w_pixel_z: 0.02 # weight to Pixel error in z -0.001
    w_cable_1_vel: 5 # weight to Joint-1 Velocity 0.8
    w_cable_2_vel: 5 # weight to Joint-2 Velocity 0.8
    w_cable_3_vel: 5 # weight to Joint-2 Velocity 0.8
    w_cable_1_accl: 1 # weight to Joint-1 acceleration
    w_cable_2_accl: 1 # weight to Joint-2 acceleration
    w_cable_3_accl: 1 # weight to Joint-2 acceleration
    pixel_x_lb: 0 # Pixel x Lower bound 
    pixel_x_ub: 640 # Pixel x Upper bound 
    pixel_y_lb: 0 # Pixel y Lower bound 
    pixel_y_ub: 480 # Pixel y Upper bound 
    cable_lengths_lb: 30  # Minimum Cable length 
    cable_lengths_ub: 2000 # Maximum Cable length 
    motor_vel_lb: -10000 # Motors angular velocity Lower bound 
    motor_vel_ub:  10000 # Motors angular velocity Upper bound 

              





 
