3linkbot :
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30  

  # Velocity Controllers ------------------------------------
  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}                         #pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  # Position Controllers ------------------------------------
  joint1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint1
    pid: {p: 1.0, i: 0.00, d: 0.1}

  joint2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0.00, d: 0.1}
  
  joint3_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint3
    pid: {p: 1.0, i: 0.00, d: 0.1}

# Jacobian Estimation Parameters ------------------------------------
  estimation:
    epsilon: 1.0e-5 # update threshold or convergence condition
    gamma:  10.0e-1 # learning rate during initial estimation
    gamma2: 10.0e-9 # learning rate during servoing
    window: 120 # window size
    rate: 10 # control rate
    amplitude: 0.4
    
  control:
    # no_of_actuators: 2
    # no_of_features: 2
    # gain_sm: -5
    thresh: 50 # Stop updating Jacobian
    goal_pos_x: 600       # This is for adaptive VS
    goal_pos_y: 500       # This is for adaptive VS
    window: 120 # window size
    lam: -0.1 # servoing gain

# Shape Servoing Parameters -------------------------------------------
  
  shape_control:
    sat: 50
    no_of_features: 8    # Number of features used for estimating the Jacobian
    no_of_actuators: 3    
    num_of_segments: 2    # Number of polynomial segments in B-spline
    degree: 3           # Degree of polynomial segments in B-spline
    beta: 1.0 # threshold for selective Jacobian update
    joint1_goal: 1.6
    joint2_goal: -0.6
    joint3_goal: -0.5
    # goal_features: [188.64980355218717, 95.64862776116439, 130.0, 65.0] 
                    # vector for storing goal features
                    # discarding last two features
                    # to be consistent with rest of the code
                    

# Goal Position for End Effector ------------------------------------

  vs_baseline:
     goal_position_x: 96 # x co-ordinates 
     goal_position_y: 166 # Y co-ordinates
     pub_rate: 10 # image Publisher rate
     j2_gain: 1
     j4_gain: 1
     xdot_gain: 0.001
     ydot_gain: 0.001

 
