vsdepth :
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30  

  # Velocity Controllers ------------------------------------
  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}                         #pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  # Position Controllers ------------------------------------
  joint1_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint1
    pid: {p: 1.0, i: 0.00, d: 0.1}

  joint2_position_controller:
    type: velocity_controllers/JointPositionController
    joint: joint2
    pid: {p: 1.0, i: 0.00, d: 0.1}

# Jacobian Estimation Parameters ------------------------------------
  estimation:
    epsilon: 1.0e-5 # update threshold or convergence condition
    gamma: 10.0e-1 # learning rate
    gamma2: 10.0e-9 # learning rate during servoing
    window: 30 # window size
    rate: 10 # initialization loop rate
    
  control:
    gain_sm: -5
    rate: 30 # control loop rate
    thresh: 25 # visual servoing convergence threshold
    goal_pos_x: 145
    goal_pos_y: 166
    window: 30 # window size
    # lam: 10.0e-4 # servoing gain
    lam: 1

# Shape Servoing Parameters -------------------------------------------
  
  shape_control:  
    
    # cropper: [250, 50, 280, 170]
    # cropper: [257, 19, 362, 224]
    # cropper: [89, 34, 506, 271]
    # cropper: [148, 54, 385, 213]
    cropper: [112, 61, 355, 260]
    no_of_features: 6
    no_of_actuators: 2
    num_of_segments: 3
    beta: 1.0 # threshold for selective Jacobian update
    joint1_goal: 1.2
    joint2_goal: 1.4
    dmin: 2
    dmax: 5
    kernel1: 9
    kernel2: 9
    # del_index: [68,  68,  68,  69,  69,  69,  69,  69,  69,  69,  69,  69,  69,
    #     69,  69,  69,  69,  69,  69,  69,  69,  69,  70,  70,  70,  70,
    #     70,  70,  71,  71,  71,  72,  72,  72,  72,  72,  72,  73,  73,
    #     74,  74,  74,  74,  74,  75,  75,  75,  75,  75,  75,  75,  75,
    #     75,  75,  75,  75,  75,  75,  75,  75,  75,  75,  75,  75,  75,
    #     75,  75,  75,  75,  75,  75,  75,  75,  75,  75,  75,  76,  76,
    #     76,  76,  76,  76,  76,  76,  76,  76,  76,  76,  76,  77,  77,
    #     77,  78,  78,  78,  78,  78,  79,  79,  80,  80,  80,  80,  80,
    #     80,  80,  81,  81,  81,  81,  82,  82,  82,  83,  83,  84,  84,
    #     85,  85,  86,  86,  87,  87,  87,  88,  88,  88,  89,  89,  90,
    #     90,  91,  91,  91,  92,  92,  92,  93,  93,  94,  94,  95,  95,
    #     96,  96,  97,  97,  98,  98,  99,  99, 100, 100, 101, 101, 102,
    #    102, 103, 103, 104, 104, 105, 105, 106, 106, 107, 107, 108, 108,
    #    109, 109, 110, 110, 111, 111, 112, 112, 113, 113, 114, 114, 115,
    #    115, 116, 116, 117, 117, 118, 118]
    # goal_features: [188.64980355218717, 95.64862776116439, 130.0, 65.0] 
                    # vector for storing goal features
                    # discarding last two features
                    # to be consistent with rest of the code
                    

# Goal Position for End Effector ------------------------------------

  vs_baseline:
    
     goal_position_x: 96 # x co-ordinates 
     goal_position_y: 166 # Y co-ordinates
     pub_rate: 30 # image Publisher rate