origami_vs:
  
  goal_pose_x: 0
  goal_pose_y: 0

  control_rate: 30

  lambda: 1

  init_max_length_hi: 0
  init_max_length_lo: 160
  init_min_length_hi: 0
  init_min_length_lo: 40




origami_adaptive_vs:
  lambda: 1


origami_skeleton_vs:
  lambda: 1