//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class GetDepthMapResponse : Message
    {
        public const string k_RosMessageName = "ur3_moveit/GetDepthMap";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.CompressedImageMsg depthmap;
        public Sensor.CameraInfoMsg camerainfo;

        public GetDepthMapResponse()
        {
            this.depthmap = new Sensor.CompressedImageMsg();
            this.camerainfo = new Sensor.CameraInfoMsg();
        }

        public GetDepthMapResponse(Sensor.CompressedImageMsg depthmap, Sensor.CameraInfoMsg camerainfo)
        {
            this.depthmap = depthmap;
            this.camerainfo = camerainfo;
        }

        public static GetDepthMapResponse Deserialize(MessageDeserializer deserializer) => new GetDepthMapResponse(deserializer);

        private GetDepthMapResponse(MessageDeserializer deserializer)
        {
            this.depthmap = Sensor.CompressedImageMsg.Deserialize(deserializer);
            this.camerainfo = Sensor.CameraInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.depthmap);
            serializer.Write(this.camerainfo);
        }

        public override string ToString()
        {
            return "GetDepthMapResponse: " +
            "\ndepthmap: " + depthmap.ToString() +
            "\ncamerainfo: " + camerainfo.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
