//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class getPointCloudRequest : Message
    {
        public const string k_RosMessageName = "ur3_moveit/getPointCloud";
        public override string RosMessageName => k_RosMessageName;

        public bool send;

        public getPointCloudRequest()
        {
            this.send = false;
        }

        public getPointCloudRequest(bool send)
        {
            this.send = send;
        }

        public static getPointCloudRequest Deserialize(MessageDeserializer deserializer) => new getPointCloudRequest(deserializer);

        private getPointCloudRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.send);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.send);
        }

        public override string ToString()
        {
            return "getPointCloudRequest: " +
            "\nsend: " + send.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
