//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class getPointCloudResponse : Message
    {
        public const string k_RosMessageName = "ur3_moveit/getPointCloud";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.PointCloud2Msg cloud;

        public getPointCloudResponse()
        {
            this.cloud = new Sensor.PointCloud2Msg();
        }

        public getPointCloudResponse(Sensor.PointCloud2Msg cloud)
        {
            this.cloud = cloud;
        }

        public static getPointCloudResponse Deserialize(MessageDeserializer deserializer) => new getPointCloudResponse(deserializer);

        private getPointCloudResponse(MessageDeserializer deserializer)
        {
            this.cloud = Sensor.PointCloud2Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cloud);
        }

        public override string ToString()
        {
            return "getPointCloudResponse: " +
            "\ncloud: " + cloud.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
