//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class getrgbimageResponse : Message
    {
        public const string k_RosMessageName = "ur3_moveit/getrgbimage";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.CompressedImageMsg rgbimage;
        public Sensor.CameraInfoMsg rgbcamerainfo;

        public getrgbimageResponse()
        {
            this.rgbimage = new Sensor.CompressedImageMsg();
            this.rgbcamerainfo = new Sensor.CameraInfoMsg();
        }

        public getrgbimageResponse(Sensor.CompressedImageMsg rgbimage, Sensor.CameraInfoMsg rgbcamerainfo)
        {
            this.rgbimage = rgbimage;
            this.rgbcamerainfo = rgbcamerainfo;
        }

        public static getrgbimageResponse Deserialize(MessageDeserializer deserializer) => new getrgbimageResponse(deserializer);

        private getrgbimageResponse(MessageDeserializer deserializer)
        {
            this.rgbimage = Sensor.CompressedImageMsg.Deserialize(deserializer);
            this.rgbcamerainfo = Sensor.CameraInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rgbimage);
            serializer.Write(this.rgbcamerainfo);
        }

        public override string ToString()
        {
            return "getrgbimageResponse: " +
            "\nrgbimage: " + rgbimage.ToString() +
            "\nrgbcamerainfo: " + rgbcamerainfo.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
