//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class MoveRobotRequest : Message
    {
        public const string k_RosMessageName = "ur3_moveit/MoveRobot";
        public override string RosMessageName => k_RosMessageName;

        public Moveit.RobotTrajectoryMsg[] trajectories;

        public MoveRobotRequest()
        {
            this.trajectories = new Moveit.RobotTrajectoryMsg[0];
        }

        public MoveRobotRequest(Moveit.RobotTrajectoryMsg[] trajectories)
        {
            this.trajectories = trajectories;
        }

        public static MoveRobotRequest Deserialize(MessageDeserializer deserializer) => new MoveRobotRequest(deserializer);

        private MoveRobotRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectories, Moveit.RobotTrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.trajectories);
            serializer.Write(this.trajectories);
        }

        public override string ToString()
        {
            return "MoveRobotRequest: " +
            "\ntrajectories: " + System.String.Join(", ", trajectories.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
