//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class MoverServiceRequest : Message
    {
        public const string k_RosMessageName = "ur3_moveit/MoverService";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose_1;
        public Geometry.PoseMsg pose_2;

        public MoverServiceRequest()
        {
            this.pose_1 = new Geometry.PoseMsg();
            this.pose_2 = new Geometry.PoseMsg();
        }

        public MoverServiceRequest(Geometry.PoseMsg pose_1, Geometry.PoseMsg pose_2)
        {
            this.pose_1 = pose_1;
            this.pose_2 = pose_2;
        }

        public static MoverServiceRequest Deserialize(MessageDeserializer deserializer) => new MoverServiceRequest(deserializer);

        private MoverServiceRequest(MessageDeserializer deserializer)
        {
            this.pose_1 = Geometry.PoseMsg.Deserialize(deserializer);
            this.pose_2 = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose_1);
            serializer.Write(this.pose_2);
        }

        public override string ToString()
        {
            return "MoverServiceRequest: " +
            "\npose_1: " + pose_1.ToString() +
            "\npose_2: " + pose_2.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
