//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class PoseEstimationServiceResponse : Message
    {
        public const string k_RosMessageName = "ur3_moveit/PoseEstimationService";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg estimated_pose;

        public PoseEstimationServiceResponse()
        {
            this.estimated_pose = new Geometry.PoseMsg();
        }

        public PoseEstimationServiceResponse(Geometry.PoseMsg estimated_pose)
        {
            this.estimated_pose = estimated_pose;
        }

        public static PoseEstimationServiceResponse Deserialize(MessageDeserializer deserializer) => new PoseEstimationServiceResponse(deserializer);

        private PoseEstimationServiceResponse(MessageDeserializer deserializer)
        {
            this.estimated_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.estimated_pose);
        }

        public override string ToString()
        {
            return "PoseEstimationServiceResponse: " +
            "\nestimated_pose: " + estimated_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
