//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class PoseEstimationServiceRequest : Message
    {
        public const string k_RosMessageName = "ur3_moveit/PoseEstimationService";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.ImageMsg image;

        public PoseEstimationServiceRequest()
        {
            this.image = new Sensor.ImageMsg();
        }

        public PoseEstimationServiceRequest(Sensor.ImageMsg image)
        {
            this.image = image;
        }

        public static PoseEstimationServiceRequest Deserialize(MessageDeserializer deserializer) => new PoseEstimationServiceRequest(deserializer);

        private PoseEstimationServiceRequest(MessageDeserializer deserializer)
        {
            this.image = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.image);
        }

        public override string ToString()
        {
            return "PoseEstimationServiceRequest: " +
            "\nimage: " + image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
