//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class resetRobotRequest : Message
    {
        public const string k_RosMessageName = "ur3_moveit/resetRobot";
        public override string RosMessageName => k_RosMessageName;

        public bool reset;

        public resetRobotRequest()
        {
            this.reset = false;
        }

        public resetRobotRequest(bool reset)
        {
            this.reset = reset;
        }

        public static resetRobotRequest Deserialize(MessageDeserializer deserializer) => new resetRobotRequest(deserializer);

        private resetRobotRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.reset);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.reset);
        }

        public override string ToString()
        {
            return "resetRobotRequest: " +
            "\nreset: " + reset.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
