//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur3Moveit
{
    [Serializable]
    public class resetRobotResponse : Message
    {
        public const string k_RosMessageName = "ur3_moveit/resetRobot";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public resetRobotResponse()
        {
            this.success = false;
        }

        public resetRobotResponse(bool success)
        {
            this.success = success;
        }

        public static resetRobotResponse Deserialize(MessageDeserializer deserializer) => new resetRobotResponse(deserializer);

        private resetRobotResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "resetRobotResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
