# physical robot
# Kp_shz: 10.0

# topic names for interacting with Panda:
vs_numjoints: 7
vs_numfingers: 2
camera_focal_length: 6.5 # 554.254691 # assumed pixels from normal gazebo cam
joint_states_topic: "/panda/joint_states"
dq1_topic: "/panda/joint1_velocity_controller/command"
dq2_topic: "/panda/joint2_velocity_controller/command"
dq3_topic: "/panda/joint3_velocity_controller/command"
dq4_topic: "/panda/joint4_velocity_controller/command"
dq5_topic: "/panda/joint5_velocity_controller/command"
dq6_topic: "/panda/joint6_velocity_controller/command"
dq7_topic: "/panda/joint7_velocity_controller/command"
finger1_topic: "/panda/panda_finger1_controller/command"
finger2_topic: "/panda/panda_finger2_controller/command"
left_camera_topic: "/multisense/camera/left/image_raw"
right_camera_topic: "/multisense/camera/right/image_raw"
